In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

/Users/alishgiri/PycharmProjects/pythonProject/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
df=pd.read_csv('/Users/alishgiri/Downloads/insurance_data.csv')

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
x_train,x_test,y_train,y_test=train_test_split(df[['age', 'affordibility']],df.bought_insurance,test_size=0.2,random_state=0)

In [5]:
x_train['age']/=100
x_test['age']/=100

In [6]:
x_train.head()

age  affordibility
24  0.50              1
13  0.29              0
20  0.21              1
25  0.54              1
16  0.25              0

In [7]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [8]:
model=Sequential(
    [
        Dense(units=1,input_shape=(2,),activation='sigmoid',bias_initializer='zeros',kernel_initializer='ones')
    ]
)

/Users/alishgiri/PycharmProjects/pythonProject/.venv/lib/python3.9/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [9]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [27]:
model.fit(x_train,y_train,epochs=6000)

Epoch 1/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7727 - loss: 0.6162
Epoch 2/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7727 - loss: 0.6162
Epoch 3/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7727 - loss: 0.6161
Epoch 4/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7727 - loss: 0.6161
Epoch 5/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7727 - loss: 0.6160
Epoch 6/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7727 - loss: 0.6160
Epoch 7/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7727 - loss: 0.6160
Epoch 8/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7727 - loss: 0.6159
Epoch 9/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7727 - loss: 0.6159
Epoch 10/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7727 - loss: 0.6158
Epoch 11/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7727 - loss: 0.6158
Epoch 12/6000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy:

In [11]:
model.evaluate(x_test,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8333 - loss: 0.6061


[0.6060981154441833, 0.8333333134651184]

In [12]:
def sigmoid(X):
    return 1/(1+np.exp(-X)) 
sigmoid(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [13]:
def logloss(y_train,y_predicted):
    eplsion=1e-15
    y_predicted=[max(i,eplsion) for i in y_predicted]
    y_predicted=[min(i,1-eplsion)for i in y_predicted]
    y_predicted=np.array(y_predicted)

    return -np.mean(
        y_train*np.log(y_predicted)+(1-y_train)*np.log(1-y_predicted)
    )
    

In [35]:
class mmy:
    def __init__(self):
        self.w1=1
        self.w2=1
        self.b=0
    def fit(self,x_train,y_train,ephos,threshold):
        self.w1,self.w2,self.b=self.gradient(x_train,y_train,ephos,threshold)
        
    def predict(self,x_varible):
        weight_sum=self.w1*x_varible.age+self.w2*x_varible.affordibility+self.b
        return sigmoid(weight_sum)
    def evaluate(self,x_test,y_test):
        y_predict=self.predict(x_test)
        error=np.mean((y_predict-y_test)**2)/2
        return error
        
    def gradient(self,x_train,y_train,ephos,threshold):
        w1=w2=1
        b=0
        rate=0.5
        n=len(x_train.age)
        for i in range(ephos):
            weight_sum=w1*x_train.age+w2*x_train.affordibility+b
            y_predicted=sigmoid(weight_sum)
            loss=logloss(y_train,y_predicted)
            w1d = (1/n)*np.dot(np.transpose(x_train.age),(y_predicted-y_train)) 
            w2d = (1/n)*np.dot(np.transpose(x_train.affordibility),(y_predicted-y_train)) 
    
            b1= np.mean(y_predicted-y_train)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            b=b-rate*b1
            print(f'w1={w1},w2={w2},b={b},loss={loss},ephos={i}')   
            if loss<=threshold:
                break
             
        return w1,w2,b
        
    

In [36]:
instanet=mmy()
instanet.fit(x_train,y_train,5000,0.4231)

w1=0.9644915668168719,w2=0.9224250019701856,b=-0.1521744437835525,loss=0.7960362503355486,ephos=0
w1=0.9366743363654499,w2=0.8570969777186894,b=-0.2838815971644586,loss=0.7394293670708099,ephos=1
w1=0.9160190930945576,w2=0.8035200242324965,b=-0.39666489545168215,loss=0.6980698848391689,ephos=2
w1=0.9017701861063159,w2=0.7606695089288332,b=-0.4926120466423785,loss=0.6686193819406211,ephos=3
w1=0.8930731543176172,w2=0.7272344982483193,b=-0.5740228037875161,loss=0.6479960845015644,ephos=4
w1=0.8890759364765384,w2=0.7018265973050505,b=-0.6431543649176596,loss=0.6336578618954344,ephos=5
w1=0.8889918350364354,w2=0.6831195783238423,b=-0.7020686534913516,loss=0.6236667598398874,ephos=6
w1=0.8921292648124785,w2=0.6699231996615574,b=-0.7525646139800298,loss=0.6166236529551378,ephos=7
w1=0.8978991061148435,w2=0.6612102292494013,b=-0.796166156177148,loss=0.6115548071590621,ephos=8
w1=0.9058095436860383,w2=0.6561158934541762,b=-0.8341401994960707,loss=0.6077987023723792,ephos=9
w1=0.915455220090085

In [40]:
instanet.predict(x_train)

24    0.691443
13    0.143199
20    0.258585
25    0.743350
16    0.114503
1     0.114503
10    0.223433
27    0.634204
26    0.283931
8     0.828725
6     0.469738
4     0.634204
18    0.080882
19    0.223433
9     0.819427
7     0.549718
23    0.619199
3     0.422229
0     0.271072
21    0.121169
15    0.755396
12    0.128167
dtype: float64

In [38]:
model.get_weights()

[array([[6.3758345],
        [1.2685363]], dtype=float32),
 array([-3.649606], dtype=float32)]

In [42]:
model.predict(x_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[0.649211  ],
       [0.5422152 ],
       [0.6776711 ],
       [0.7886679 ],
       [0.7666333 ],
       [0.35529694]], dtype=float32)

In [ ]:
instanet.evaluate(x_test,y_test)